### ISSUE TITLE
How to autoplay this swiper?

### ISSUE THREAD

**Issue by nive745** [logisticinfotech/react-native-custom-swiper#1]
I want to autoplay swiper. How can i implement autoplay functionality.

Thanks in advance

**Comment by nileshkikani** [comment]
Hello @nive745 
Thanks for using this package, We will upload it on next version. 

Thanks.

**Comment by nive745** [comment]
Thanks for reply @nileshkikani 
When will you upload new version any idea? ;)
Because my client need it soon. Do give me idea how to implement it? I will contribute to this package.

**Comment by nileshkikani** [comment]
@nive745 We will upload within  couple of working day.

**Comment by nileshkikani** [comment]
@nive745 If you wish and want to continue with this library then you can fork from current and do required changes at your side later you can generate PR and I will validate PR and publish it.

**Comment by nive745** [comment]
@nileshkikani 
Ok. Thank you nilesh. i will update you by email. I am also from saurastra.

**Comment by nive745** [comment]
Hi @nileshkikani,
I committed my code and compete autoswipe functionality to master please validate PR and publish it.
Thank you,
Nikhil Thaker

**Comment by nileshkikani** [comment]
@nive745 I am not seeing your PR request. Can you please check at your side? Let me assign you rights to push in git.
