### ISSUE TITLE
TaskQueue: Error with task : undefined is not a function (evaluation '_iterator[typeof Symbol....

### ISSUE THREAD

**Issue by nive745** [logisticinfotech/react-native-custom-swiper#4]
![screenshot_1549375378](https://user-images.githubusercontent.com/17614227/52278928-4282d780-297e-11e9-843a-af3f784f4392.png)

undefined is not a function (evaluating '_iterator2[typeof Symbol === "function" ? Symbol.iterator : "@@iterator"]()'
I got this error only in android. 
Do you have any idea about it?

Thanks,
Nikhil Thaker

**Comment by nive745** [comment]
[](url)

**Comment by nileshkikani** [comment]
@nive745 can you provide me more detail on how are you using this and where you get that error.
